name: Build Android application on new tag
run-name: Building CalcMoney (${{ github.ref_name }})
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # force download all commits

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Set Version Variables
        run: |
          # VERSION_NAME
          TAG_NAME="${{ github.ref_name }}"
          echo "VERSION_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "VERSION_NAME=$TAG_NAME"
          
          # VERSION_CODE
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "VERSION_CODE=$COMMIT_COUNT" >> $GITHUB_ENV
          echo "VERSION_CODE=$COMMIT_COUNT"

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease -PVERSION_NAME="${{ env.VERSION_NAME }}" -PVERSION_CODE="${{ env.VERSION_CODE }}"

      - name: Sign Android APK
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > calcmoney-key.jks
          
          APK_PATH=$(find app/build/outputs/apk/release/app-release*.apk | head -n 1)
          echo "--> APK located at $APK_PATH"
          
          # Retrieve latest Android BuildTools installed
          echo "--> ANDROID_HOME=$ANDROID_HOME"
          BUILD_TOOLS_DIR=$(ls -d $ANDROID_HOME/build-tools/* | tail -n 1)
          echo "--> Using build-tools at: $BUILD_TOOLS_DIR"
          
          # Align APK (output file at working dir)
          $BUILD_TOOLS_DIR/zipalign -v 4 "$APK_PATH" calcmoney-aligned.apk
          
          # Sign APK (output file at working dir)
          $BUILD_TOOLS_DIR/apksigner sign \
            --ks calcmoney-key.jks \
            --ks-key-alias "${{ secrets.ALIAS }}" \
            --ks-pass "pass:${{ secrets.KEY_STORE_PASSWORD }}" \
            --key-pass "pass:${{ secrets.KEY_PASSWORD }}" \
            --out calcmoney-${{ github.ref_name }}.apk \
            calcmoney-aligned.apk
          
          rm calcmoney-key.jks
          rm calcmoney-aligned.apk

      - name: Generate Changelog
        run: |
          # Retrieve previous tag (if there is one)
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          
          if [ -z "$PREV_TAG" ]; then
            CHANGELOG=$(git log --pretty=format:"- %s")
          else
            CHANGELOG=$(git log --pretty=format:"- %s" "$PREV_TAG..HEAD")
          fi
          
          # Creating multi-line variable
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v3
        with:
          files: calcmoney-*.apk
          name: Release ${{ github.ref_name }}
          body: |
            ### What's new ?
            
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false